"""Recipe request/response schemas.

The recipe Pydantic models are defined centrally in ``app.schemas.recipe``
(they are also consumed by ``app.services.ai_service``). This module re-exports
them so the recipes package follows the same router / service / schemas layout
as the other feature packages, while keeping a single source of truth.
"""
from app.schemas.recipe import (
    RecipeCreate,
    RecipeBatchCreate,
    RecipeUpdate,
    RecipeUpdateIngredients,
    RecipeResponse,
    RecipeListItem,
    RecipeListResponse,
    RecipeScaledResponse,
    RecipeIngredientScaled,
    RecipeFilters,
    CookingHistoryCreate,
    CookingHistoryResponse,
    CookingHistoryListResponse,
    RecipeCollectionCreate,
    RecipeCollectionUpdate,
    RecipeCollectionResponse,
    RecipeCollectionWithRecipes,
    AddToCollectionRequest,
    RemoveFromCollectionRequest,
    BulkActionRequest,
    BulkActionResponse,
    RecipeAnalytics,
    RecipesByCategory,
    RecipesByCuisine,
    RecipesByDifficulty,
    MostCookedRecipe,
    RecipeHistory,
    MonthlyRecipeData,
    ParseRecipeTextRequest,
    ParseRecipeUrlRequest,
    ParseRecipeResponse,
    AddToShoppingListRequest,
    RecipeSuggestionRequest,
    RecipeSuggestionItem,
    RecipeSuggestionResponse,
    RecipeAvailabilityStatus,
    RecipeIngredientAvailability,
)

__all__ = [
    "RecipeCreate",
    "RecipeBatchCreate",
    "RecipeUpdate",
    "RecipeUpdateIngredients",
    "RecipeResponse",
    "RecipeListItem",
    "RecipeListResponse",
    "RecipeScaledResponse",
    "RecipeIngredientScaled",
    "RecipeFilters",
    "CookingHistoryCreate",
    "CookingHistoryResponse",
    "CookingHistoryListResponse",
    "RecipeCollectionCreate",
    "RecipeCollectionUpdate",
    "RecipeCollectionResponse",
    "RecipeCollectionWithRecipes",
    "AddToCollectionRequest",
    "RemoveFromCollectionRequest",
    "BulkActionRequest",
    "BulkActionResponse",
    "RecipeAnalytics",
    "RecipesByCategory",
    "RecipesByCuisine",
    "RecipesByDifficulty",
    "MostCookedRecipe",
    "RecipeHistory",
    "MonthlyRecipeData",
    "ParseRecipeTextRequest",
    "ParseRecipeUrlRequest",
    "ParseRecipeResponse",
    "AddToShoppingListRequest",
    "RecipeSuggestionRequest",
    "RecipeSuggestionItem",
    "RecipeSuggestionResponse",
    "RecipeAvailabilityStatus",
    "RecipeIngredientAvailability",
]
