"""Meal plan request/response schemas.

The meal plan Pydantic models are defined centrally in
``app.schemas.meal_plan`` (they are also consumed by
``app.services.ai_service``). This module re-exports them so the meal_plans
package follows the same router / service / schemas layout as the other
feature packages, while keeping a single source of truth.
"""
from app.schemas.meal_plan import (
    MealCreate,
    MealUpdate,
    MealResponse,
    MealPlanCreate,
    MealPlanUpdate,
    MealPlanResponse,
    MealPlanWithMeals,
    MealPlanListItem,
    MealPlanListResponse,
    MealPlanFilters,
    MealBulkCreate,
    RepeatMealPlanRequest,
    BulkMealActionRequest,
    BulkMealPlanActionRequest,
    BulkActionResponse,
    MealPlanAnalytics,
    MealsByType,
    MealsByRecipe,
    WeeklyOverview,
    MealPlanHistory,
    MonthlyMealPlanData,
    GenerateShoppingListRequest,
    GenerateShoppingListResponse,
    ShoppingListPreviewResponse,
    ShoppingListItemPreview,
    ParseMealPlanTextRequest,
    ParseMealPlanResponse,
    ParsedMealPlanMeal,
    CombinedWeekPlan,
    MealWithProfile,
    ProfileInfo,
    MarkMealCookedRequest,
    MarkMealCookedResponse,
    IngredientDeductionSummary,
    MealAvailabilityResponse,
    MealIngredientAvailability,
    SimpleMealCreate,
    SimpleMealUpdate,
    SimpleMealResponse,
    WeekMealsResponse,
)

__all__ = [
    "MealCreate",
    "MealUpdate",
    "MealResponse",
    "MealPlanCreate",
    "MealPlanUpdate",
    "MealPlanResponse",
    "MealPlanWithMeals",
    "MealPlanListItem",
    "MealPlanListResponse",
    "MealPlanFilters",
    "MealBulkCreate",
    "RepeatMealPlanRequest",
    "BulkMealActionRequest",
    "BulkMealPlanActionRequest",
    "BulkActionResponse",
    "MealPlanAnalytics",
    "MealsByType",
    "MealsByRecipe",
    "WeeklyOverview",
    "MealPlanHistory",
    "MonthlyMealPlanData",
    "GenerateShoppingListRequest",
    "GenerateShoppingListResponse",
    "ShoppingListPreviewResponse",
    "ShoppingListItemPreview",
    "ParseMealPlanTextRequest",
    "ParseMealPlanResponse",
    "ParsedMealPlanMeal",
    "CombinedWeekPlan",
    "MealWithProfile",
    "ProfileInfo",
    "MarkMealCookedRequest",
    "MarkMealCookedResponse",
    "IngredientDeductionSummary",
    "MealAvailabilityResponse",
    "MealIngredientAvailability",
    "SimpleMealCreate",
    "SimpleMealUpdate",
    "SimpleMealResponse",
    "WeekMealsResponse",
]
